config/routes.rb
PhotoAlbum::Application.routes.draw do
match 'photos/show' => 'photos#show', :as => :show_photo
match 'albums/show' => 'albums#show', :as => :show_album
  resources :albums, :shallow => true do
  resources :photos
  end
resources :photos
root :to => "albums#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
    validates_presence_of :directory, :title
    has_many :photos, :dependent => :destroy
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
    @output = "<div ><br><table  class='entries'><br><tr>"
    10.times { |i| @output.concat("<th></th>") }
    @output.concat("</tr></tr>")
    irc = 0
    @album.photos.each do |photo|
      irc += 1
      @output.concat( "<td><div class='thumbnail'><a href='/photos/show?id=".concat(photo.id.to_s) )
      @output.concat( "'><img class='icons' src='/images/".concat(photo.path) )
      @output.concat( "/".concat(photo.image))
      @output.concat( "'  /></a></div></td>\n")
      if irc == 10
        irc = 0
        @output.concat( "</tr>\n<tr>" )
      end
    end
    @output.concat( "</tr>\n</table>\n</div>" )
   # respond_to do |format|
   #   format.html # show.html.erb
      #format.json { render json: @album }
  # end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        #Dir.chdir("public/images")
        Dir.mkdir(@album['directory'])
        flash[:notice] = 'Album was successfully created.'
        #flash[:notice] = Dir.pwd
        format.html { redirect_to @album }
        #format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action = "new" }
        #format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        flash[:notice] = 'Album was successfully updated.'
        format.html { redirect_to @album }
        format.json { head :no_content }
      else
        format.html { render action = "edit" }
       # format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy
   # Dir.chdir("public/images")
    Dir.delete(@album['directory'])

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper :all # include all helpers, all the time
    protect_from_forgery
    before_filter :authenticate, :except => [:index, :show]
    private

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "teilnehmer"
      end
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  before_filter :authenticate, :except => [:index, :show ]

    def index
      @photos = Photo.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @photos }
      end
    end

    # GET /photos/1
    # GET /photos/1.json
    def show
      @photo = Photo.find(params[:id])
      @album = Album.new(params[:album])
      @output = '<div class="thumbnail">'
      @output.concat( "<a href='/albums/show?id=".concat(@photo.album_id.to_s) )
      @output.concat( "' /a>\n<img src='/images/" + @photo.path + "/".concat(@photo.image) )
      @output.concat( "' /></div>" )

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @photo }
      end
    end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
       format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
       # format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
       # format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
       # format.json { head :no_content }
      else
        format.html { render action: "edit" }
       # format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
     # format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cover_image %><br />
    <%= f.text_field :cover_image %>
  </div>
  <div class="field">
    <%= f.label :directory %><br />
    <%= f.text_field :directory %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/_photoset.html.erb
<h2>Photos</h2>
<%= @output.html_safe %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Eugene's Photo Album</h1>

<table class="entries">
  <tr>
    <th>Title</th>
    <th></th>
    <th>Directory</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td class="entries"><%= album.title %></td>
    <td class="entries"><div class='thumbnail'><a href='/albums/show?id=<%= album.id.to_s %>'><img class='icons' src='<%= "images/" + album.directory + "/" + album.cover_image  %>' /></a></div></td>
    <td class="entries"><%= album.directory %></td>
    <td class="oblique"><%= utc_time = Time.parse(album.created_at.to_s).utc; utc_time.localtime; date = DateTime.parse(utc_time.localtime.to_s); date.strftime('%a %b %d %H:%M:%S') %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @album.title %></h1>

<p>
  <b>Directory:</b>
  <%= @album.directory %>
</p>

<p>
  <b>Content:</b>
  <%= @album.content %>
</p>

<p>
  <b>Created at:</b>
  <%= utc_time = Time.parse(@album.created_at.to_s).utc; utc_time.localtime; date = DateTime.parse(utc_time.localtime.to_s); date.strftime('%a %b %d %H:%M:%S') %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

<%= render :partial => 'photoset' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eugene's PhotoAlbum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style='padding-top: 40px;'>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :album_id %><br />
    <%= f.number_field :album_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Index of Images</h1>
<%= link_to 'Albums', albums_path %>
<p>
<table class="entries">
  <tr>
    <th>Title</th>
    <th>Image</th>
    <th>Path</th>
    <th>Content</th>
    <th>Album</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.title.to_s.sub(/^---\s\S\s/,'') %></td>
    <td><%= photo.image %></td>
    <td><%= photo.path %></td>
    <td><%= photo.content %></td>
    <td><%= photo.album_id %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Details</h2>
<p>
  <b>Photo Id:</b>
  <%= @photo.title.to_s.sub(/^---\s\S\s/,'') %>
</p>
<p>
  <b>Album:</b>
  <%= @photo.path %>
</p>
<table class="entries">
<tr><td>
<%= @output.html_safe %>
</td></tr>
</table>
<p>
  <b>Description:</b>
  <%= @photo.content %>
</p>
<p>
  <b>Created at:</b>
  <%= utc_time = Time.parse(@photo.created_at.to_s).utc; utc_time.localtime; date = DateTime.parse(utc_time.localtime.to_s); date.strftime('%a %b %d %H:%M:%S') %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Index', photos_path %> |
<%= link_to 'Album', show_album_path(:id =>@photo.album_id) %>